### ISSUE TITLE
Conversion of LaTeX comments

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patadata#20]
Dans certains chants les commentaires sont en anglais et en français.

Le format ChrodPro n'est pas vraiment fait pour supporter cela : je propose de garder seulement le commentaire fait dans la langue de la chanson (je suppose qu'un personne qui veut chanter un chant anglais à un niveau suffisant pour comprendre le commentaire en anglais).

PS : cela concerne uniquement les chants où les commentaires sont dans les deux langues, mais on pourrait adopter cette convention pour les futurs commentaires

**Comment by Luthaf** [comment]
Je suis d'accord avec cette solution. C'est plus simple que d'essayer de supporter plusieurs langues dans les commentaires.
