### ISSUE TITLE
Package keyval Error: cover undefined.

### ISSUE THREAD

**Issue by renard** [patacrep/patadata#31]
Je tente de compiler le songbook et j'obtient l'erreur:

```
! Package keyval Error: cover undefined.

See the keyval package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.4 ...-},cover={je-dis-aime},album={Je dis aime}]
```

Visiblement il faudrait supprimer tous les `cover=` comme donné par le patch suivant, et ce pour toutes les chansons.

```diff
diff --git a/songs/m/je_dis_aime.sg b/songs/m/je_dis_aime.sg
index dd616e7..8af535d 100644
--- a/songs/m/je_dis_aime.sg
+++ b/songs/m/je_dis_aime.sg
@@ -1,7 +1,7 @@
 \selectlanguage{french}
 \songcolumns{2}
 \beginsong{Je dis aime}
-  [by={-M-},cover={je-dis-aime},album={Je dis aime}]
+  [by={-M-},album={Je dis aime}]

   \cover
   \gtab{Em}{022000}
```

Mais je me dis qu'il devrait exister une manière plus élégante de faire en sorte de pouvoir compiler le songbook et que j'ai du louper quelque chose.

J'utilise:

```
songbook --version
songbook 4.0.0
```
installé via `pip3`

Merci d'avance.

**Comment by oliverpool** [comment]
C'est de notre faute, patacrep est en train de changer... (mais la version de développement n'est pas installable par `pip3`).

J'ai fait la modification fautive (https://github.com/patacrep/patadata/commit/98c5dd31bd108ef2066846c088a42781648325e3) dans `patadata` sans y faire attention: il faudrait utiliser une version antérieure à ce changement (disponible ici par exemple : https://github.com/patacrep/patadata/tree/47bcb7fc93d27df0884041b136e24c2496dfb341)

**Comment by renard** [comment]
C'est mieux en effet. Merci.

En revanche les images provoquent des erreurs:

```

! LaTeX Error: File `nb_dwarf_02' not found.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.49   \image[width=4cm]{nb_dwarf_02}
```

Cela fonctionne si:
* on désactive les images (bouhhh)
* on met le chemin vers l'image: `songs/le_donjon_de_naheulbeuk/nb_dwarf_02` (moyennement propre).

C'est surement une option d'inclusion qui manque.

**Comment by paternal** [comment]
Je n'ai pas ce problème avec la version de développement (master) de patacrep.

J'ai bien peur que ce soit la même chose : nous avons reporté dans patadata des modifications de patanet avant al publication de la prochaine version de patacrep. Pas très sérieux tout ça…

**Comment by oliverpool** [comment]
@renard tu peux essayer avec une version encore antérieure : 
https://github.com/patacrep/patadata/tree/2eaa3ab5ca4be6a5e0791763c3b0acd2ac60af58

(mais cette fois-ci, c'est @paternal le fautif https://github.com/patacrep/patadata/commit/e60f037d73ea3b22d48d87942a4dc2a8e0ce7571 ;-)

*Cela rajoute la commande `\currfile`*

**Comment by oliverpool** [comment]
@renard Ca y est, la version 5.0 est désormais la version officielle !

Selon comment tu as installé patacrep, c'est une bonne idée de le mettre à jour (par exemple `pip3 install patacrep -U`).

J'ai réussi à compiler la version `master` de patadata avec aujourd'hui même :-)

**Comment by renard** [comment]
Oui c'est mieux ça a marché tout (presque) seul. Bravo!

en revanche j'ai des bugs d'affichage, je fais un ticket à part.
