### ISSUE TITLE
Problème d'encodage dans la table des matières PDF

### ISSUE THREAD

**Issue by renard** [patacrep/patadata#41]
Je viens d'installer la dernière version de pataXX de la manière suivante (sous Mac OS X):

```
git clone https://github.com/patacrep/patadata.git
git clone https://github.com/patacrep/patacrep.git
cd patacrep
python -m patacrep.songbook ../patadata/books/songbook_fr.yaml
INFO:patacrep.build:Building 'songbook_fr.tex'…
INFO:patacrep.build:Building 'songbook_fr.pdf'…
INFO:patacrep.build:Building indexes…
INFO:patacrep.build:Building 'songbook_fr.pdf'…
INFO:patacrep.build:Cleaning…
```

Tout se passe nickel le PDF sort tout beau.

... Mais l'encodage des titres dans la TOC ne se fait pas correctement:

<img width="1124" alt="screen shot 2016-06-10 at 15 32 26" src="https://cloud.githubusercontent.com/assets/383821/15966078/bbc77df8-2f21-11e6-9b2a-2b350f9ffa3c.png">

**Comment by oliverpool** [comment]
J'ai eu le même soucis avec evince, mais ça se passait bien avec un autre lecteur pdf (Sumatra sous windows il me semble).

J'essayerai de creuser à l'occasion !

**Comment by oliverpool** [comment]
La capture d'écran est pour quel logiciel ?

**Comment by renard** [comment]
@oliverpool c'est Preview, l'application par défaut de Mac OS X

**Comment by renard** [comment]
@oliverpool c'est surement un problème lié à l'encodage latex directement.

On a moyen de conserver les fichiers générés pour analyse post-mortem?

**Comment by Luthaf** [comment]
`python -m patacrep.songbook --steps tex,pdf,sbx,pdf ../patadata/books/songbook_fr.yaml` devriat faire l'affaire. La doc en question [est ici](https://patacrep.readthedocs.io/fr/latest/bin.html#cmdoption-songbook--steps) =)

**Comment by oliverpool** [comment]
J'ai trouvé une solution potentielle : https://github.com/patacrep/patacrep/pull/225

@renard tu peux le tester en changeant la branche de patacrep:
```sh
git fetch origin
git checkout bookmark_encoding_fix
```
