### ISSUE TITLE
List of authors that refuse to be included

### ISSUE THREAD

**Issue by Grahack** [patacrep/patadata#49]
Hi,
Suppose I want to contribute with a few songs. I make a nice PR for them. Then you decide not to merge the PR because the author of the songs already contacted you and stated she doesn't want to have songs in `patacrep` songbooks.

1. Has it already occured?
1. Is there a list of such authors?

**Comment by oliverpool** [comment]
> Has it already occured?
> Is there a list of such authors?

Not that I knew.

Cf:
- https://github.com/patacrep/patanet/issues/74
- https://github.com/patacrep/patanet/issues/16
- https://github.com/patacrep/patanet/issues/97

**Comment by Grahack** [comment]
Thanks for the refs.
